import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "../app/globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gradient-to-b from-slate-900 to-slate-700 overflow-hidden">
      <body className='bg-gradient-to-b from-slate-900 to-slate-700 overflow-hidden flex flex-col'>
        {children}
      </body>
    </html>
  );
}
